### ISSUE TITLE
Add plugin failed with 'Method not found: ... ZipFile.OpenRead...'

### ISSUE THREAD

**Issue by GordPollock-AI** [AquaticInformatics/aquarius-field-data-framework#38] opened 2018-12-13 22:37 UTC
Downloaded FieldDataPluginTool.exe v18.3.2 to desktop of v18.3 development aqts server vm. Ran as administrator. Could connect to database, reorder plugins.
When I clicked "Add..." and selected FlowTracker2Plugin.plugin, it popped up an error dialog. "Method not found: 'System.IO.Compression.ZipArchive System.IO.Compression.Zipfile.OpenRead(System.String)'."

After I installed the development version of v18.4 it was able to open plugin files.

Succeeded in installing the plugin by using version v18.1.1. I suspect this is because it's distributed in a zip with FieldDataPluginTool.exe.config beside the exe.

**Comment by kmkobayashi** [comment] 2018-12-30 22:10
I am having this issue as well with 18.3.1 and 18.3.2.  I can successfully reorder plugins, but I am running into the error mentioned above while trying to add a plugin. 

This was on a AQ TS 2018.3 server.  I am on .net 4.7.2.  Is there possibly another dependency or configuration I am missing, having only downloaded the fielddataplugintool.exe and the target .plugin file?  Someone at AQ mentioned I might need VS installed, but this seems like it should be unnecessary. 

It was mentioned above that GordPollock-AI had Success with the 18.4 dev version.  Is this version stable enough that I should feel confident trying it out?

**Comment by DougSchmidt-AI** [comment] 2018-12-31 23:20
Hi Kenji.

I haven't been able to reproduce this bug on any of my systems here. I know it happens, I just am having difficulty tracking down the exact cause. That will likely change when more of the devs return from vacation in a few days.

But there are a few options you can try right now, while I'm trying to sort things out:

1) Give the latest [v18.4.0](https://github.com/AquaticInformatics/aquarius-field-data-framework/releases/download/v18.4.0/FieldDataPluginTool.exe) a try

I did a bit of cleanup today, and it *might* have fixed the issue. It's worth a quick try. v18.4.0 of the FieldDataPluginTool.exe works with AQTS server all the way back to v2017.4.

2) If that doesn't work, try placing this file right next to the v18.4.0 `FieldDataPluginTool.exe`

This `*.exe.config` file should force the tool to use the correct .NET runtime (4.7.2), which contains the missing compression library.

3) If that *still* doesn't work, use the older [v18.1.1](https://github.com/AquaticInformatics/aquarius-field-data-framework/releases/download/v18.1.1/FieldDataPluginTool.zip) tool, which gave Gord success

Gord actually used this older version of the tool to work with his 18.3 and 18.4 AQTS systems. (It's easy to get the version numbers for big AQTS product and the tiny `FieldDataPluginTool.exe` download confused. Sorry about that)

This older version was distributed as a ZIP archive, not an EXE, so you'll need to extract all the files to a folder somewhere. But as Gord mentioned, one of those files is the `FieldDataPluginTool.exe.config` file, which seems to be correlated to a succesful installation experience.

Keep me posted about what you find out.

Cheers,
Doug

**Comment by kmkobayashi** [comment] 2019-01-02 16:06
Just an update.  I tried version 18.4 and it went through just fine.  As far as I have been able to tell there have been no other issues or errors.  So, just to reaffirm, version 18.4 seems to not have this issue.

**Comment by DougSchmidt-AI** [comment] 2019-01-02 16:16
Thanks for the feedback Kenji.

**Comment by DougSchmidt-AI** [comment] 2019-03-04 17:03
I'm going to close this issue for now, since the 18.4 release also supported plugin uploads directly via curl or the Swagger UI page.

**Closed by DougSchmidt-AI** 2019-03-04 17:03 UTC
