### ISSUE TITLE
Saving parsed data would result in duplicates

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-field-data-framework#62] opened 2019-04-17 19:27 UTC
I'm developing a plugin to import csv files where there is Visit information, something similar to flowtraker2. When I try to add vertical information I always get the following error:
`Saving parsed data would result in duplicates`
In fact, I just tried the flowtracker2 files (Demo.ft) and I also get the same error.
It happens even if there are no visits in the location.
I've tried everything I can think of, but I can't fix it. I think it has something to do with the calibration but I'm not sure.
Could you help me with this?

AQUARIUS SERVER version 18.4.80
FlowTracker2 plugin release version 17.4.44

![chrome_2019-04-17_21-20-48](https://user-images.githubusercontent.com/14314396/56315110-332ac200-6157-11e9-9ee9-5ed42ca87285.png)
![chrome_2019-04-17_21-21-01](https://user-images.githubusercontent.com/14314396/56315115-36be4900-6157-11e9-84a9-90b4f028cb56.png)
![chrome_2019-04-17_21-21-26](https://user-images.githubusercontent.com/14314396/56315123-3920a300-6157-11e9-9982-bfcd6ce333bd.png)

Server error:
```
2019-04-17T19:13:37.661Z [26472-250] INFO  Server.BusinessObjects.FieldDataPlugin.Context.PluginFileSubmitter - Plugin FlowTracker2 parsed file "DemoData.ft" of size 336 KB in parse context <global> with status SuccessfullyParsedAndDataValid in 264 ms elapsed and 281 ms CPU
2019-04-17T19:13:37.755Z [26472-250] ERROR Server.Adapters.OrmLite.ProfiledDbCommandWithLogging - dbConn=64632569: Failed to execute command: INSERT INTO MeterCalibrationEquation (Id,MeterCalibrationId,RangeStart,RangeEnd,Slope,Intercept,InterceptUnitId) VALUES (:Id,:MeterCalibrationId,:RangeStart,:RangeEnd,:Slope,:Intercept,:InterceptUnitId)
::Id:Int64=56
::MeterCalibrationId:Int64=105
::RangeStart:Double=
::RangeEnd:Double=
::Slope:Double=0
::Intercept:Double=0
::InterceptUnitId:String=ft
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00001: unique constraint (AQUARIUS.PK_METERCALIEQUATION) violated
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at ServiceStack.MiniProfiler.Data.ProfiledCommand.ExecuteNonQuery()
   at ServiceStack.MiniProfiler.Data.ProfiledCommand.ExecuteNonQuery()
   at Server.Adapters.OrmLite.ProfiledDbCommandWithLogging.ExecuteNonQuery()
2019-04-17T19:13:37.755Z [26472-250] INFO  Server.Adapters.OrmLite.RepositoryBase - ORA-00001: unique constraint (AQUARIUS.PK_METERCALIEQUATION) violated
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00001: unique constraint (AQUARIUS.PK_METERCALIEQUATION) violated
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at ServiceStack.MiniProfiler.Data.ProfiledCommand.ExecuteNonQuery()
   at ServiceStack.MiniProfiler.Data.ProfiledCommand.ExecuteNonQuery()
   at Server.Adapters.OrmLite.ProfiledDbCommandWithLogging.ExecuteNonQuery()
   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   at Server.Adapters.FieldVisit.MeterCalibrationRepository.InsertCalibrationEquations(IDbConnection connection, IEnumerable`1 meterCalibrationEquations, Int64 meterCalibrationId)
   at Server.Adapters.FieldVisit.MeterCalibrationRepository.<>c__DisplayClass18_0.<InsertMeterCalibration>b__0(IDbConnection connection)
   at Server.Adapters.OrmLite.RepositoryBase.RunDbMethod[TResult](Func`2 func)
2019-04-17T19:13:37.755Z [26472-250] INFO  Server.BusinessObjects.FieldDataPlugin.FieldDataPluginAccess - Failed to save visits from plugin FlowTracker2, file "DemoData.ft" due to error: Saving parsed data would result in duplicates

```

**Comment by DougSchmidt-AI** [comment] 2019-04-22 23:51
Hi @edgarbelda.

Yeah, that stack trace looks like it is somehow related to the meter calibration DTO. That seems unexpected to me, especially if that location doesn't contain any visits, but clearly it is occuring for you.

Can you use the `PluginTester.exe` tool (it's downloaded with the Aquarius.FieldDataFramework Nuget package) to load your plugin, parse that CSV file, and create a JSON output file? That will contain the exact data being sent into the framework, and if you attach the JSON file to this issue, I should be able to reproduce it here.

Note that GitHub doesn't let you attach "*.json" files by default, so you'll need to rename the file extension to .txt in order to attach it.

If you've built your plugin in Debug mode using Visual Studio, then this CMD block should invoke the PluginTester will the required arguments to generate the JSON file (you may need to change some paths):
```cmd
C:\some folder\git\myPlugin\src\myPlugin\bin\Debug> ..\..\..\packages\Aquarius.FieldDataFramework.18.4.3\tools\PluginTester.exe -plugin=myPlugin.dll -data=..\..\..\..\data\C4002_404693.csv -json=AppendedResults.json.txt
16:47:41.717 INFO  - Loading data file '..\..\..\..\data\C4002_404693.csv'
16:47:41.845 INFO  - Saving 1 visits data to 'AppendedResults.json.txt'
16:47:41.938 INFO  - Successfully parsed 1 visits from '..\..\..\..\data\C4002_404693.csv'.
```

That should create a `AppendedResults.json.txt` file in the same folder as your plugin DLL's Debug build, and you should be able to drag and drop that file onto this issue as a new comment.

**Comment by edgarbelda** [comment] 2019-04-23 18:44
Hi @DougSchmidt-AI 
I always use PluginTester both for debugging and also in building events. It is very useful to check what information has been extracted and if everything has worked correctly.
For developing that plugin I'm using Aquarius.FieldDataFramework.17.4.0. because it has to works in other out-of-date server too. 
**I attach here the result file:**
[AppendedResults.json.txt](https://github.com/AquaticInformatics/aquarius-field-data-framework/files/3109048/AppendedResults.json.txt)

Also I tried with the JSONplugin but I got the same error:
![chrome_2019-04-23_20-33-33](https://user-images.githubusercontent.com/14314396/56606804-521dce00-6607-11e9-8363-34a6e0fb724f.png)

**Comment by DougSchmidt-AI** [comment] 2019-04-23 19:05
Thanks, I'll take a look.

**Comment by DougSchmidt-AI** [comment] 2019-04-23 19:26
After I created a location named "C4002", I was able to import the JSON using the new [JSON field data plugin](https://github.com/AquaticInformatics/aquarius-field-data-framework/blob/master/src/JsonFieldData/Readme.md)

![image](https://user-images.githubusercontent.com/54773/56608949-ce40f300-65c0-11e9-89d6-ece753a28467.png)

So that tells me your plugin is creating good data so far.

Here's the resulting panel measurement:

![image](https://user-images.githubusercontent.com/54773/56609113-34c61100-65c1-11e9-9eb5-931d63b7e6b6.png)

I also tried deleting that new visit and trying again to import it, but the 2nd import also worked fine.

My app server is running 2018.4.80, so I don't know if an earlier version of AQTS has a bug that the newer version does not. I won't be able to test on a version before 2018.4, because the JSON plugin needs 2018.4.

Hmm. Can you send me the lastest `FieldDataPluginFramework.log` and `DataService.log` files from the `%ProgramData%\Aquatic Informatics\AQUARIUS\Logs` folder on the app server? There might be some clue nearby in the exception stack trace.

Your initial issue already included a relevant stack trace, so I'm not hopeful we'll find something new by looking at the entire file, but maybe we'll get lucky. Sometimes the `DataService.log` can contain a bit more context for failed file uploads.

**Comment by edgarbelda** [comment] 2019-04-24 15:53
Your screenshot looks nice. At least the plugin is working fine.

I attach here the log files (I truncated DataService.log because it's very big)
[FieldDataPluginFramework.log.txt](https://github.com/AquaticInformatics/aquarius-field-data-framework/files/3113128/FieldDataPluginFramework.log.txt)
[DataService.log.txt](https://github.com/AquaticInformatics/aquarius-field-data-framework/files/3113085/DataService.log.txt)

This error is happening in a updated server (2018.4.80).
![mstsc_2019-04-24_17-39-54](https://user-images.githubusercontent.com/14314396/56673547-bfd60280-66b8-11e9-8cac-2dafc0b49615.png)

The error may be due to problems with the installation. But I have no idea.

**Comment by DougSchmidt-AI** [comment] 2019-04-24 19:44
I had a further look. I think your system is somehow driving an unknown bug in the actual product. I want to escalate this to the dev team. Can you open a support case in our Salesforce Customer Support portal? I can add the necessary details to that case.

**Comment by DougSchmidt-AI** [comment] 2019-04-24 20:30
Can you also download and run the [SystemSizer.exe](https://github.com/AquaticInformatics/getting-started/releases/tag/SystemSizer) tool on your app server, and attach the `SystemSizer.log` output to the salesforce case? That will give us some basic info on the configuration of your app server and your database.

**Comment by DougSchmidt-AI** [comment] 2019-04-30 17:00
I'm going to close this issue, since we've determined it was due to a corrupt DB restore.

**Closed by DougSchmidt-AI** 2019-04-30 17:00 UTC
